name = "plaid-docs-mcp"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "DOCS_KV"
id = "bfc62559ce5c452bb0e7a54c3220ae03"

[durable_objects]
bindings = [
  { name = "MCP_AGENT", class_name = "PlaidDocsMcp" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PlaidDocsMcp"]
